CREATE TABLE bookmarks (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  description TEXT NULL,
  rating INTEGER NOT NULL
)

-- bookmarks_assgn, bookmarks_test